//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksUniqueRoutesPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksUniqueRoutesPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed points outside band.
        /// </summary>
        internal static string AllowPointsOutsideBand {
            get {
                return ResourceManager.GetString("AllowPointsOutsideBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth.
        /// </summary>
        internal static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth must be a number..
        /// </summary>
        internal static string BandwidthWarning {
            get {
                return ResourceManager.GetString("BandwidthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore beginning meters must be a number..
        /// </summary>
        internal static string BeginningMeterWarning {
            get {
                return ResourceManager.GetString("BeginningMeterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find any other activities on same route.\nIf you think there should be some, please adjust the settings and try again..
        /// </summary>
        internal static string DidNotFindAnyRoutes {
            get {
                return ResourceManager.GetString("DidNotFindAnyRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do it!.
        /// </summary>
        internal static string DoIt {
            get {
                return ResourceManager.GetString("DoIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore end meters must be a number..
        /// </summary>
        internal static string EndMeterWarning {
            get {
                return ResourceManager.GetString("EndMeterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} other activities on same route..
        /// </summary>
        internal static string FoundActivities {
            get {
                return ResourceManager.GetString("FoundActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore beginning of route.
        /// </summary>
        internal static string IgnoreBeginningOfRoute {
            get {
                return ResourceManager.GetString("IgnoreBeginningOfRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore end of route.
        /// </summary>
        internal static string IgnoreEndOfRoute {
            get {
                return ResourceManager.GetString("IgnoreEndOfRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all activities in search.
        /// </summary>
        internal static string IncludeAllActivitiesInSearch {
            get {
                return ResourceManager.GetString("IncludeAllActivitiesInSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include only activities in category &apos;{0}&apos; in search.
        /// </summary>
        internal static string IncludeOnlyCategory {
            get {
                return ResourceManager.GetString("IncludeOnlyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in applying the {0} plugin. Low-level error message: {1}.
        /// </summary>
        internal static string PluginApplicationError {
            get {
                return ResourceManager.GetString("PluginApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes have direction.
        /// </summary>
        internal static string RoutesHaveDirection {
            get {
                return ResourceManager.GetString("RoutesHaveDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Routes plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
    }
}
