//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksUniqueRoutesPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksUniqueRoutesPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activities to.
        /// </summary>
        internal static string ActivitiesTo {
            get {
                return ResourceManager.GetString("ActivitiesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed points outside band.
        /// </summary>
        internal static string AllowPointsOutsideBand {
            get {
                return ResourceManager.GetString("AllowPointsOutsideBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. HR..
        /// </summary>
        internal static string AvgHR {
            get {
                return ResourceManager.GetString("AvgHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth.
        /// </summary>
        internal static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth must be a number..
        /// </summary>
        internal static string BandwidthWarning {
            get {
                return ResourceManager.GetString("BandwidthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore beginning meters must be a number..
        /// </summary>
        internal static string BeginningMeterWarning {
            get {
                return ResourceManager.GetString("BeginningMeterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change category.
        /// </summary>
        internal static string ChangeCategory {
            get {
                return ResourceManager.GetString("ChangeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find any other activities on same route.\nIf you think there should be some, please adjust the settings and try again..
        /// </summary>
        internal static string DidNotFindAnyRoutes {
            get {
                return ResourceManager.GetString("DidNotFindAnyRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do it!.
        /// </summary>
        internal static string DoIt {
            get {
                return ResourceManager.GetString("DoIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore end meters must be a number..
        /// </summary>
        internal static string EndMeterWarning {
            get {
                return ResourceManager.GetString("EndMeterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} other activities on same route..
        /// </summary>
        internal static string FoundActivities {
            get {
                return ResourceManager.GetString("FoundActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string HourShort {
            get {
                return ResourceManager.GetString("HourShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore beginning of route.
        /// </summary>
        internal static string IgnoreBeginningOfRoute {
            get {
                return ResourceManager.GetString("IgnoreBeginningOfRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore end of route.
        /// </summary>
        internal static string IgnoreEndOfRoute {
            get {
                return ResourceManager.GetString("IgnoreEndOfRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all activities in search.
        /// </summary>
        internal static string IncludeAllActivitiesInSearch {
            get {
                return ResourceManager.GetString("IncludeAllActivitiesInSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include only activities in category &apos;{0}&apos; in search.
        /// </summary>
        internal static string IncludeOnlyCategory {
            get {
                return ResourceManager.GetString("IncludeOnlyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pace.
        /// </summary>
        internal static string LowerCasePace {
            get {
                return ResourceManager.GetString("LowerCasePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteShort {
            get {
                return ResourceManager.GetString("MinuteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        internal static string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percent.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in applying the {0} plugin. Low-level error message: {1}.
        /// </summary>
        internal static string PluginApplicationError {
            get {
                return ResourceManager.GetString("PluginApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings....
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes have direction.
        /// </summary>
        internal static string RoutesHaveDirection {
            get {
                return ResourceManager.GetString("RoutesHaveDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5c630517-46c4-478d-89d6-a8a6ca6337db}.
        /// </summary>
        internal static string UniqueRoutesGuid {
            get {
                return ResourceManager.GetString("UniqueRoutesGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string UnitCentimeter {
            get {
                return ResourceManager.GetString("UnitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string UnitCentimeterShort {
            get {
                return ResourceManager.GetString("UnitCentimeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fod.
        /// </summary>
        internal static string UnitFoot {
            get {
                return ResourceManager.GetString("UnitFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fod.
        /// </summary>
        internal static string UnitFootShort {
            get {
                return ResourceManager.GetString("UnitFootShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomme.
        /// </summary>
        internal static string UnitInch {
            get {
                return ResourceManager.GetString("UnitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomme.
        /// </summary>
        internal static string UnitInchShort {
            get {
                return ResourceManager.GetString("UnitInchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer.
        /// </summary>
        internal static string UnitKilometer {
            get {
                return ResourceManager.GetString("UnitKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string UnitKilometerShort {
            get {
                return ResourceManager.GetString("UnitKilometerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string UnitMeter {
            get {
                return ResourceManager.GetString("UnitMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string UnitMeterShort {
            get {
                return ResourceManager.GetString("UnitMeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mil.
        /// </summary>
        internal static string UnitMile {
            get {
                return ResourceManager.GetString("UnitMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string UnitMileShort {
            get {
                return ResourceManager.GetString("UnitMileShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard.
        /// </summary>
        internal static string UnitYard {
            get {
                return ResourceManager.GetString("UnitYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string UnitYardShort {
            get {
                return ResourceManager.GetString("UnitYardShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all categories.
        /// </summary>
        internal static string UseAllCategories {
            get {
                return ResourceManager.GetString("UseAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Routes plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
    }
}
