//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksAccumulatedSummaryPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksAccumulatedSummaryPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {859F81F4-8272-4183-BA53-FDF1DD809FD6}.
        /// </summary>
        internal static string AccumulatedSummaryGuid {
            get {
                return ResourceManager.GetString("AccumulatedSummaryGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Summary of one activity.
        /// </summary>
        internal static string AS1 {
            get {
                return ResourceManager.GetString("AS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Summary of {0} activities.
        /// </summary>
        internal static string AS2 {
            get {
                return ResourceManager.GetString("AS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average heart rate.
        /// </summary>
        internal static string AverageHR {
            get {
                return ResourceManager.GetString("AverageHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb up/down ({0}).
        /// </summary>
        internal static string Climb {
            get {
                return ResourceManager.GetString("Climb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb zones.
        /// </summary>
        internal static string ClimbZones {
            get {
                return ResourceManager.GetString("ClimbZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd:.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest pace.
        /// </summary>
        internal static string FastestsPace {
            get {
                return ResourceManager.GetString("FastestsPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastests speed ({0}/h).
        /// </summary>
        internal static string FastestsSpeed {
            get {
                return ResourceManager.GetString("FastestsSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate zones (BPM) ({0}).
        /// </summary>
        internal static string HeartRateZones {
            get {
                return ResourceManager.GetString("HeartRateZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_AccumulatedSummary {
            get {
                object obj = ResourceManager.GetObject("Image_16_AccumulatedSummary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_AccumulatedSummary {
            get {
                object obj = ResourceManager.GetObject("Image_24_AccumulatedSummary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_AccumulatedSummary {
            get {
                object obj = ResourceManager.GetObject("Image_32_AccumulatedSummary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging.
        /// </summary>
        internal static string Jogging {
            get {
                return ResourceManager.GetString("Jogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm:.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} activities used.
        /// </summary>
        internal static string NoutofM {
            get {
                return ResourceManager.GetString("NoutofM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace (min/{0}).
        /// </summary>
        internal static string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed ({0}/h).
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed zones.
        /// </summary>
        internal static string SpeedZones {
            get {
                return ResourceManager.GetString("SpeedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ({0}).
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string UnitCentimeter {
            get {
                return ResourceManager.GetString("UnitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string UnitCentimeterShort {
            get {
                return ResourceManager.GetString("UnitCentimeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        internal static string UnitFoot {
            get {
                return ResourceManager.GetString("UnitFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string UnitFootShort {
            get {
                return ResourceManager.GetString("UnitFootShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string UnitInch {
            get {
                return ResourceManager.GetString("UnitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string UnitInchShort {
            get {
                return ResourceManager.GetString("UnitInchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer.
        /// </summary>
        internal static string UnitKilometer {
            get {
                return ResourceManager.GetString("UnitKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string UnitKilometerShort {
            get {
                return ResourceManager.GetString("UnitKilometerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string UnitMeter {
            get {
                return ResourceManager.GetString("UnitMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string UnitMeterShort {
            get {
                return ResourceManager.GetString("UnitMeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile.
        /// </summary>
        internal static string UnitMile {
            get {
                return ResourceManager.GetString("UnitMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string UnitMileShort {
            get {
                return ResourceManager.GetString("UnitMileShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard.
        /// </summary>
        internal static string UnitYard {
            get {
                return ResourceManager.GetString("UnitYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string UnitYardShort {
            get {
                return ResourceManager.GetString("UnitYardShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        internal static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Summary plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
    }
}
