//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsRunningPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpsRunningPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biggest elevation difference.
        /// </summary>
        internal static string BiggestElevationDifference {
            get {
                return ResourceManager.GetString("BiggestElevationDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to distances..
        /// </summary>
        internal static string CannotAddToDistances {
            get {
                return ResourceManager.GetString("CannotAddToDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to elevations..
        /// </summary>
        internal static string CannotAddToElevations {
            get {
                return ResourceManager.GetString("CannotAddToElevations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to heart rates. From and to BPM must be positive numbers, and from must be smaller than to..
        /// </summary>
        internal static string CannotAddToHRZones {
            get {
                return ResourceManager.GetString("CannotAddToHRZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to paces. From and to must be a time in the format mm:ss, and from time must be faster than to time..
        /// </summary>
        internal static string CannotAddToPaceZones {
            get {
                return ResourceManager.GetString("CannotAddToPaceZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to paces. From and to must be positive numbers, and from number must be slower than to number..
        /// </summary>
        internal static string CannotAddToSpeedZones {
            get {
                return ResourceManager.GetString("CannotAddToSpeedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to times..
        /// </summary>
        internal static string CannotAddToTimes {
            get {
                return ResourceManager.GetString("CannotAddToTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to had manual entered data.
        /// </summary>
        internal static string HadManualEnteredData {
            get {
                return ResourceManager.GetString("HadManualEnteredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to had no start time.
        /// </summary>
        internal static string HadNoStartTime {
            get {
                return ResourceManager.GetString("HadNoStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR. &amp; speed zone.
        /// </summary>
        internal static string HRAndSpeedZones {
            get {
                return ResourceManager.GetString("HRAndSpeedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score.
        /// </summary>
        internal static string HS {
            get {
                return ResourceManager.GetString("HS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score view.
        /// </summary>
        internal static string HSV {
            get {
                return ResourceManager.GetString("HSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored {0} activities.
        /// </summary>
        internal static string IgnoredActivities {
            get {
                return ResourceManager.GetString("IgnoredActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored activities with manual entered data.
        /// </summary>
        internal static string IgnoreManualEnteredBox {
            get {
                return ResourceManager.GetString("IgnoreManualEnteredBox", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_HighScore {
            get {
                object obj = ResourceManager.GetObject("Image_16_HighScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_HighScore {
            get {
                object obj = ResourceManager.GetObject("Image_24_HighScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_HighScore {
            get {
                object obj = ResourceManager.GetObject("Image_32_HighScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest distance traveled.
        /// </summary>
        internal static string LongestDistanceTraveled {
            get {
                return ResourceManager.GetString("LongestDistanceTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest time spent.
        /// </summary>
        internal static string LongestTimeSpent {
            get {
                return ResourceManager.GetString("LongestTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for this settings..
        /// </summary>
        internal static string NoResultsForSettings {
            get {
                return ResourceManager.GetString("NoResultsForSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display for this setting..
        /// </summary>
        internal static string NothingToDisplay {
            get {
                return ResourceManager.GetString("NothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a distance of.
        /// </summary>
        internal static string OnADistanceOf {
            get {
                return ResourceManager.GetString("OnADistanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on an elevation of.
        /// </summary>
        internal static string OnAnElevationOf {
            get {
                return ResourceManager.GetString("OnAnElevationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a time of.
        /// </summary>
        internal static string OnATimeOf {
            get {
                return ResourceManager.GetString("OnATimeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current settings and use the default settings instead?.
        /// </summary>
        internal static string ResetAllSettingsWarning {
            get {
                return ResourceManager.GetString("ResetAllSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current distances and return to default distances?.
        /// </summary>
        internal static string ResetDistancesWarning {
            get {
                return ResourceManager.GetString("ResetDistancesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current elevations and return to default elevations?.
        /// </summary>
        internal static string ResetElevationsWarning {
            get {
                return ResourceManager.GetString("ResetElevationsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current heart rate zones and return to default heart rate zones?.
        /// </summary>
        internal static string ResetHRZonesWarning {
            get {
                return ResourceManager.GetString("ResetHRZonesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current pace zones and return to default pace zones?.
        /// </summary>
        internal static string ResetPaceZonesWarning {
            get {
                return ResourceManager.GetString("ResetPaceZonesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current times and return to default times?.
        /// </summary>
        internal static string ResetTimesWarning {
            get {
                return ResourceManager.GetString("ResetTimesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest distance traveled.
        /// </summary>
        internal static string ShortestDistanceTraveled {
            get {
                return ResourceManager.GetString("ShortestDistanceTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest time spent.
        /// </summary>
        internal static string ShortestTimeSpent {
            get {
                return ResourceManager.GetString("ShortestTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest elevation difference.
        /// </summary>
        internal static string SmallestElevationDifference {
            get {
                return ResourceManager.GetString("SmallestElevationDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a heart rate between.
        /// </summary>
        internal static string WithAHRBetween {
            get {
                return ResourceManager.GetString("WithAHRBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a pace between.
        /// </summary>
        internal static string WithAPaceBetween {
            get {
                return ResourceManager.GetString("WithAPaceBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a speed between.
        /// </summary>
        internal static string WithASpeedBetween {
            get {
                return ResourceManager.GetString("WithASpeedBetween", resourceCulture);
            }
        }
    }
}
