//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksHighScorePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksHighScorePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. HR..
        /// </summary>
        internal static string AverageHR {
            get {
                return ResourceManager.GetString("AverageHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biggest elevation difference.
        /// </summary>
        internal static string BiggestElevationDifference {
            get {
                return ResourceManager.GetString("BiggestElevationDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM from.
        /// </summary>
        internal static string BPMFrom {
            get {
                return ResourceManager.GetString("BPMFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM to.
        /// </summary>
        internal static string BPMTo {
            get {
                return ResourceManager.GetString("BPMTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to distances..
        /// </summary>
        internal static string CannotAddToDistances {
            get {
                return ResourceManager.GetString("CannotAddToDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to elevations..
        /// </summary>
        internal static string CannotAddToElevations {
            get {
                return ResourceManager.GetString("CannotAddToElevations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to heart rates. From and to BPM must be positive numbers, and from must be smaller than to..
        /// </summary>
        internal static string CannotAddToHRZones {
            get {
                return ResourceManager.GetString("CannotAddToHRZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to paces. From and to must be a time in the format mm:ss, and from time must be faster than to time..
        /// </summary>
        internal static string CannotAddToPaceZones {
            get {
                return ResourceManager.GetString("CannotAddToPaceZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to paces. From and to must be positive numbers, and from number must be slower than to number..
        /// </summary>
        internal static string CannotAddToSpeedZones {
            get {
                return ResourceManager.GetString("CannotAddToSpeedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add to times..
        /// </summary>
        internal static string CannotAddToTimes {
            get {
                return ResourceManager.GetString("CannotAddToTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy table to clipboard.
        /// </summary>
        internal static string CopyTable {
            get {
                return ResourceManager.GetString("CopyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances.
        /// </summary>
        internal static string Distances {
            get {
                return ResourceManager.GetString("Distances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance.
        /// </summary>
        internal static string DomDistance {
            get {
                return ResourceManager.GetString("DomDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elevation.
        /// </summary>
        internal static string DomElevation {
            get {
                return ResourceManager.GetString("DomElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string DomTime {
            get {
                return ResourceManager.GetString("DomTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevations.
        /// </summary>
        internal static string Elevations {
            get {
                return ResourceManager.GetString("Elevations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to had manual entered data.
        /// </summary>
        internal static string HadManualEnteredData {
            get {
                return ResourceManager.GetString("HadManualEnteredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to had no start time.
        /// </summary>
        internal static string HadNoStartTime {
            get {
                return ResourceManager.GetString("HadNoStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate (BPM).
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR. &amp; speed zone.
        /// </summary>
        internal static string HRAndSpeedZones {
            get {
                return ResourceManager.GetString("HRAndSpeedZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR. zone.
        /// </summary>
        internal static string HRZone {
            get {
                return ResourceManager.GetString("HRZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate zones.
        /// </summary>
        internal static string HRZones {
            get {
                return ResourceManager.GetString("HRZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score for one activity.
        /// </summary>
        internal static string HS1 {
            get {
                return ResourceManager.GetString("HS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score for {0} activities.
        /// </summary>
        internal static string HS2 {
            get {
                return ResourceManager.GetString("HS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score view of {0} activities.
        /// </summary>
        internal static string HSV1 {
            get {
                return ResourceManager.GetString("HSV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score view of one activity.
        /// </summary>
        internal static string HSV2 {
            get {
                return ResourceManager.GetString("HSV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score view of no activities.
        /// </summary>
        internal static string HSV3 {
            get {
                return ResourceManager.GetString("HSV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored {0} activities.
        /// </summary>
        internal static string IgnoredActivities {
            get {
                return ResourceManager.GetString("IgnoredActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored activities with manual entered data.
        /// </summary>
        internal static string IgnoreManualEnteredBox {
            get {
                return ResourceManager.GetString("IgnoreManualEnteredBox", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_HighScore {
            get {
                object obj = ResourceManager.GetObject("Image_16_HighScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_HighScore {
            get {
                object obj = ResourceManager.GetObject("Image_24_HighScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_HighScore {
            get {
                object obj = ResourceManager.GetObject("Image_32_HighScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest distance traveled.
        /// </summary>
        internal static string LongestDistanceTraveled {
            get {
                return ResourceManager.GetString("LongestDistanceTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest time spent.
        /// </summary>
        internal static string LongestTimeSpent {
            get {
                return ResourceManager.GetString("LongestTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string LowerCaseAnd {
            get {
                return ResourceManager.GetString("LowerCaseAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graph.
        /// </summary>
        internal static string LowerCaseGraph {
            get {
                return ResourceManager.GetString("LowerCaseGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximal.
        /// </summary>
        internal static string LowerCaseMaximal {
            get {
                return ResourceManager.GetString("LowerCaseMaximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimal.
        /// </summary>
        internal static string LowerCaseMinimal {
            get {
                return ResourceManager.GetString("LowerCaseMinimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pace.
        /// </summary>
        internal static string LowerCasePace {
            get {
                return ResourceManager.GetString("LowerCasePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        internal static string LowerCaseSpeed {
            get {
                return ResourceManager.GetString("LowerCaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table.
        /// </summary>
        internal static string LowerCaseTable {
            get {
                return ResourceManager.GetString("LowerCaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for this settings..
        /// </summary>
        internal static string NoResultsForSettings {
            get {
                return ResourceManager.GetString("NoResultsForSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display for this setting..
        /// </summary>
        internal static string NothingToDisplay {
            get {
                return ResourceManager.GetString("NothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a distance of.
        /// </summary>
        internal static string OnADistanceOf {
            get {
                return ResourceManager.GetString("OnADistanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on an elevation of.
        /// </summary>
        internal static string OnAnElevationOf {
            get {
                return ResourceManager.GetString("OnAnElevationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a time of {0} hours.
        /// </summary>
        internal static string OnATimeOfHours {
            get {
                return ResourceManager.GetString("OnATimeOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a time of {0} minutes.
        /// </summary>
        internal static string OnATimeOfMinutes {
            get {
                return ResourceManager.GetString("OnATimeOfMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a time of {0} seconds.
        /// </summary>
        internal static string OnATimeOfSeconds {
            get {
                return ResourceManager.GetString("OnATimeOfSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace min/{0}.
        /// </summary>
        internal static string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace (min/{0}).
        /// </summary>
        internal static string Pace2 {
            get {
                return ResourceManager.GetString("Pace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min/{0}.
        /// </summary>
        internal static string PaceFormat {
            get {
                return ResourceManager.GetString("PaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm:ss/min from.
        /// </summary>
        internal static string PaceLabelFrom {
            get {
                return ResourceManager.GetString("PaceLabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm:ss/min to.
        /// </summary>
        internal static string PaceLabelTo {
            get {
                return ResourceManager.GetString("PaceLabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace zones.
        /// </summary>
        internal static string PaceZones {
            get {
                return ResourceManager.GetString("PaceZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per specified.
        /// </summary>
        internal static string PerSpecified {
            get {
                return ResourceManager.GetString("PerSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset....
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings....
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current settings and use the default settings instead?.
        /// </summary>
        internal static string ResetAllSettingsWarning {
            get {
                return ResourceManager.GetString("ResetAllSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current distances and return to default distances?.
        /// </summary>
        internal static string ResetDistancesWarning {
            get {
                return ResourceManager.GetString("ResetDistancesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current elevations and return to default elevations?.
        /// </summary>
        internal static string ResetElevationsWarning {
            get {
                return ResourceManager.GetString("ResetElevationsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current heart rate zones and return to default heart rate zones?.
        /// </summary>
        internal static string ResetHRZonesWarning {
            get {
                return ResourceManager.GetString("ResetHRZonesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current pace zones and return to default pace zones?.
        /// </summary>
        internal static string ResetPaceZonesWarning {
            get {
                return ResourceManager.GetString("ResetPaceZonesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the current times and return to default times?.
        /// </summary>
        internal static string ResetTimesWarning {
            get {
                return ResourceManager.GetString("ResetTimesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest distance traveled.
        /// </summary>
        internal static string ShortestDistanceTraveled {
            get {
                return ResourceManager.GetString("ShortestDistanceTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest time spent.
        /// </summary>
        internal static string ShortestTimeSpent {
            get {
                return ResourceManager.GetString("ShortestTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest elevation difference.
        /// </summary>
        internal static string SmallestElevationDifference {
            get {
                return ResourceManager.GetString("SmallestElevationDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string SomeHours {
            get {
                return ResourceManager.GetString("SomeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string SomeMinutes {
            get {
                return ResourceManager.GetString("SomeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string SomeSeconds {
            get {
                return ResourceManager.GetString("SomeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed {0}/h.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed ({0}/h).
        /// </summary>
        internal static string Speed2 {
            get {
                return ResourceManager.GetString("Speed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/h.
        /// </summary>
        internal static string SpeedFormat {
            get {
                return ResourceManager.GetString("SpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/h from.
        /// </summary>
        internal static string SpeedLabelFrom {
            get {
                return ResourceManager.GetString("SpeedLabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/h to.
        /// </summary>
        internal static string SpeedLabelTo {
            get {
                return ResourceManager.GetString("SpeedLabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed zone.
        /// </summary>
        internal static string SpeedZone {
            get {
                return ResourceManager.GetString("SpeedZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm:ss.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (hours).
        /// </summary>
        internal static string TimeHours {
            get {
                return ResourceManager.GetString("TimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a heart rate between {0} and {1} BPM.
        /// </summary>
        internal static string WithAHRBetween {
            get {
                return ResourceManager.GetString("WithAHRBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a pace between {0} min/{1} and {2} min/{3} .
        /// </summary>
        internal static string WithAPaceBetween {
            get {
                return ResourceManager.GetString("WithAPaceBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a speed between {0} {1}/h and {2} {3}/h.
        /// </summary>
        internal static string WithASpeedBetween {
            get {
                return ResourceManager.GetString("WithASpeedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
