//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksTRIMPPlugin.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksTRIMPPlugin.Util.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Speed/Pace.
        /// </summary>
        internal static string ActivitySpeedOrPace {
            get {
                return ResourceManager.GetString("ActivitySpeedOrPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change category.
        /// </summary>
        internal static string ChangeCategory {
            get {
                return ResourceManager.GetString("ChangeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb up/down.
        /// </summary>
        internal static string ClimbSummary {
            get {
                return ResourceManager.GetString("ClimbSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb zones.
        /// </summary>
        internal static string ClimbZones {
            get {
                return ResourceManager.GetString("ClimbZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        internal static string DaysFormat {
            get {
                return ResourceManager.GetString("DaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0} activities.
        /// </summary>
        internal static string ForManyActivities {
            get {
                return ResourceManager.GetString("ForManyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for one activity.
        /// </summary>
        internal static string ForOneActivity {
            get {
                return ResourceManager.GetString("ForOneActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        internal static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh.
        /// </summary>
        internal static string HoursFormat {
            get {
                return ResourceManager.GetString("HoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR. zone.
        /// </summary>
        internal static string HRZone {
            get {
                return ResourceManager.GetString("HRZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings.
        /// </summary>
        internal static string ListSettings {
            get {
                return ResourceManager.GetString("ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathon.
        /// </summary>
        internal static string Marathon {
            get {
                return ResourceManager.GetString("Marathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal.
        /// </summary>
        internal static string Maximal {
            get {
                return ResourceManager.GetString("Maximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        internal static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string MinutesFormat {
            get {
                return ResourceManager.GetString("MinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected activity..
        /// </summary>
        internal static string NoSelectedActivities {
            get {
                return ResourceManager.GetString("NoSelectedActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} activities used.
        /// </summary>
        internal static string NoutofM {
            get {
                return ResourceManager.GetString("NoutofM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of zones:.
        /// </summary>
        internal static string NumberOfZones {
            get {
                return ResourceManager.GetString("NumberOfZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0} activities.
        /// </summary>
        internal static string OfManyActivities {
            get {
                return ResourceManager.GetString("OfManyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of no activities.
        /// </summary>
        internal static string OfNoActivities {
            get {
                return ResourceManager.GetString("OfNoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of one activity.
        /// </summary>
        internal static string OfOneActivity {
            get {
                return ResourceManager.GetString("OfOneActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per specified.
        /// </summary>
        internal static string PerSpecified {
            get {
                return ResourceManager.GetString("PerSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset....
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings....
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset all settings? This cannot be undone..
        /// </summary>
        internal static string ResetQuestion {
            get {
                return ResourceManager.GetString("ResetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        internal static string SecondsFormat {
            get {
                return ResourceManager.GetString("SecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed zone.
        /// </summary>
        internal static string SpeedZone {
            get {
                return ResourceManager.GetString("SpeedZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start zone:.
        /// </summary>
        internal static string StartZone {
            get {
                return ResourceManager.GetString("StartZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm:ss.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all categories.
        /// </summary>
        internal static string UseAllCategories {
            get {
                return ResourceManager.GetString("UseAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis.
        /// </summary>
        internal static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis.
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
    }
}
