//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksTRIMPPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksTRIMPPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current rest heart rate: {0} BPM. Maximal heart rate: {1} BPM..
        /// </summary>
        internal static string CurrentRestAndMax {
            get {
                return ResourceManager.GetString("CurrentRestAndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        internal static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate (BPM).
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored {0} activities that did not have a heart rate track..
        /// </summary>
        internal static string IgnoredActivities {
            get {
                return ResourceManager.GetString("IgnoredActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored one activity since it did not have a heart rate track..
        /// </summary>
        internal static string IgnoredActivity {
            get {
                return ResourceManager.GetString("IgnoredActivity", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_TRIMP {
            get {
                object obj = ResourceManager.GetObject("Image_16_TRIMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_TRIMP {
            get {
                object obj = ResourceManager.GetObject("Image_24_TRIMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_TRIMP {
            get {
                object obj = ResourceManager.GetObject("Image_32_TRIMP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resting or no maximal heart rate in the logbook.\nThe plugin will not do anything before a maximal heart rate is set.\nTo set this go to the athlete view..
        /// </summary>
        internal static string NoRestOrMaxHR {
            get {
                return ResourceManager.GetString("NoRestOrMaxHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected activity..
        /// </summary>
        internal static string NoSelectedActivities {
            get {
                return ResourceManager.GetString("NoSelectedActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of zones:.
        /// </summary>
        internal static string NumberOfZones {
            get {
                return ResourceManager.GetString("NumberOfZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %HR. reserve.
        /// </summary>
        internal static string PercHRReserve {
            get {
                return ResourceManager.GetString("PercHRReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %max HR..
        /// </summary>
        internal static string PercMaxHR {
            get {
                return ResourceManager.GetString("PercMaxHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings....
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset all settings? This cannot be undone..
        /// </summary>
        internal static string ResetQuestion {
            get {
                return ResourceManager.GetString("ResetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start zone:.
        /// </summary>
        internal static string StartZone {
            get {
                return ResourceManager.GetString("StartZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIMP of a single activity.
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIMP of {0} activities.
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (min).
        /// </summary>
        internal static string TimeMinutes {
            get {
                return ResourceManager.GetString("TimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total TRIMP is {0}..
        /// </summary>
        internal static string TotalTRIMP {
            get {
                return ResourceManager.GetString("TotalTRIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate reserve.
        /// </summary>
        internal static string UseHRReserve {
            get {
                return ResourceManager.GetString("UseHRReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max heart rate.
        /// </summary>
        internal static string UseMaxHR {
            get {
                return ResourceManager.GetString("UseMaxHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone (%max HR.).
        /// </summary>
        internal static string ZoneMaxHR {
            get {
                return ResourceManager.GetString("ZoneMaxHR", resourceCulture);
            }
        }
    }
}
