//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsRunningPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpsRunningPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add distance.
        /// </summary>
        internal static string AddDistance {
            get {
                return ResourceManager.GetString("AddDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted pace.
        /// </summary>
        internal static string AdjustedPace {
            get {
                return ResourceManager.GetString("AdjustedPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted speed.
        /// </summary>
        internal static string AdjustedSpeed {
            get {
                return ResourceManager.GetString("AdjustedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted time.
        /// </summary>
        internal static string AdjustedTime {
            get {
                return ResourceManager.GetString("AdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted VDOT.
        /// </summary>
        internal static string AdjustedVDOT {
            get {
                return ResourceManager.GetString("AdjustedVDOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Predictor.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance used in models.
        /// </summary>
        internal static string DistancesUsed {
            get {
                return ResourceManager.GetString("DistancesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy aerobic zone.
        /// </summary>
        internal static string EasyAerobicZone {
            get {
                return ResourceManager.GetString("EasyAerobicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of part.
        /// </summary>
        internal static string EndOfPart {
            get {
                return ResourceManager.GetString("EndOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated pace.
        /// </summary>
        internal static string EstimatedPace {
            get {
                return ResourceManager.GetString("EstimatedPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated speed.
        /// </summary>
        internal static string EstimatedSpeed {
            get {
                return ResourceManager.GetString("EstimatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time.
        /// </summary>
        internal static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High aerobic zone.
        /// </summary>
        internal static string HighAerobicZone {
            get {
                return ResourceManager.GetString("HighAerobicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score plugin integration.
        /// </summary>
        internal static string HighScorePluginIntegration {
            get {
                return ResourceManager.GetString("HighScorePluginIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score Prediction.
        /// </summary>
        internal static string HighScorePrediction {
            get {
                return ResourceManager.GetString("HighScorePrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicting using several activities requires High Score plugin.
        /// </summary>
        internal static string HighScoreRequired {
            get {
                return ResourceManager.GetString("HighScoreRequired", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_PerformancePredictor {
            get {
                object obj = ResourceManager.GetObject("Image_16_PerformancePredictor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_PerformancePredictor {
            get {
                object obj = ResourceManager.GetObject("Image_24_PerformancePredictor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_PerformancePredictor {
            get {
                object obj = ResourceManager.GetObject("Image_32_PerformancePredictor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested short interval times training for certain race distances..
        /// </summary>
        internal static string IntervalNotification {
            get {
                return ResourceManager.GetString("IntervalNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval split times.
        /// </summary>
        internal static string IntervalSplitTimes {
            get {
                return ResourceManager.GetString("IntervalSplitTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod aerobic zone.
        /// </summary>
        internal static string ModAerobicZone {
            get {
                return ResourceManager.GetString("ModAerobicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go the athlete view and set your maximal heart rate to see the results..
        /// </summary>
        internal static string NoMaxHR {
            get {
                return ResourceManager.GetString("NoMaxHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seed activity.
        /// </summary>
        internal static string NoSeedActivity {
            get {
                return ResourceManager.GetString("NoSeedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace for tempo runs.
        /// </summary>
        internal static string PaceForTempoRuns {
            get {
                return ResourceManager.GetString("PaceForTempoRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace for tempo runs of 20 to 60 minutes at VDOT {0:0.0}. 20 min run is at lactate threshold pace - pace of longer runs adjusted to maintain proper intensity..
        /// </summary>
        internal static string PaceForTempoRuns_label {
            get {
                return ResourceManager.GetString("PaceForTempoRuns_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 min run is at lactate threshold pace - pace of longer runs adjusted to maintain proper 
        ///intensity..
        /// </summary>
        internal static string PaceRunNotification {
            get {
                return ResourceManager.GetString("PaceRunNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance must be a positive number, optionally followed by the unit..
        /// </summary>
        internal static string PositiveNumber {
            get {
                return ResourceManager.GetString("PositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Predictor with High Score plugin.
        /// </summary>
        internal static string PPHS {
            get {
                return ResourceManager.GetString("PPHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted time.
        /// </summary>
        internal static string PredictedTime {
            get {
                return ResourceManager.GetString("PredictedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction model.
        /// </summary>
        internal static string PredictionModel {
            get {
                return ResourceManager.GetString("PredictionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction results.
        /// </summary>
        internal static string PredictionResults {
            get {
                return ResourceManager.GetString("PredictionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of distance to predict time.
        /// </summary>
        internal static string ProcDistUsed {
            get {
                return ResourceManager.GetString("ProcDistUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected adverse impact of high temperatures on.
        /// </summary>
        internal static string ProjectedTemperatureImpact {
            get {
                return ResourceManager.GetString("ProjectedTemperatureImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected weight.
        /// </summary>
        internal static string ProjectedWeight {
            get {
                return ResourceManager.GetString("ProjectedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected impact of weight on.
        /// </summary>
        internal static string ProjectedWeightImpact {
            get {
                return ResourceManager.GetString("ProjectedWeightImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove distance.
        /// </summary>
        internal static string RemoveDistance {
            get {
                return ResourceManager.GetString("RemoveDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to the athlete view and set your weight to see the results..
        /// </summary>
        internal static string SetWeight {
            get {
                return ResourceManager.GetString("SetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of part.
        /// </summary>
        internal static string StartOfPart {
            get {
                return ResourceManager.GetString("StartOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature impact.
        /// </summary>
        internal static string TemperatureImpact {
            get {
                return ResourceManager.GetString("TemperatureImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance is not adversely affected at {0} or lower..
        /// </summary>
        internal static string TemperatureNotification {
            get {
                return ResourceManager.GetString("TemperatureNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time prediction.
        /// </summary>
        internal static string TimePrediction {
            get {
                return ResourceManager.GetString("TimePrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train / race HR..
        /// </summary>
        internal static string TrainRaceHR {
            get {
                return ResourceManager.GetString("TrainRaceHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used activity start date.
        /// </summary>
        internal static string UsedActivityStartDate {
            get {
                return ResourceManager.GetString("UsedActivityStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used activity start time.
        /// </summary>
        internal static string UsedActivityStartTime {
            get {
                return ResourceManager.GetString("UsedActivityStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used length of activity.
        /// </summary>
        internal static string UsedLengthOfActivity {
            get {
                return ResourceManager.GetString("UsedLengthOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used time of activity.
        /// </summary>
        internal static string UsedTimeOfActivity {
            get {
                return ResourceManager.GetString("UsedTimeOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in chart.
        /// </summary>
        internal static string ViewInChart {
            get {
                return ResourceManager.GetString("ViewInChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in table.
        /// </summary>
        internal static string ViewInTable {
            get {
                return ResourceManager.GetString("ViewInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % VO2 max: {0:0.0}%, VDOT: {1:0.0}.
        /// </summary>
        internal static string VO2MaxVDOT {
            get {
                return ResourceManager.GetString("VO2MaxVDOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Predictor plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight impact.
        /// </summary>
        internal static string WeighImpact {
            get {
                return ResourceManager.GetString("WeighImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated times and paces are +/- {0} per {1}.
        /// </summary>
        internal static string WeightNotification {
            get {
                return ResourceManager.GetString("WeightNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone / distance.
        /// </summary>
        internal static string ZoneDistance {
            get {
                return ResourceManager.GetString("ZoneDistance", resourceCulture);
            }
        }
    }
}
