//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsRunningPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GpsRunningPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average over period.
        /// </summary>
        internal static string AOP {
            get {
                return ResourceManager.GetString("AOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black category average.
        /// </summary>
        internal static string BCA {
            get {
                return ResourceManager.GetString("BCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold moving average.
        /// </summary>
        internal static string BMA {
            get {
                return ResourceManager.GetString("BMA", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_Overlay {
            get {
                object obj = ResourceManager.GetObject("Image_16_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_Overlay {
            get {
                object obj = ResourceManager.GetObject("Image_24_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_Overlay {
            get {
                object obj = ResourceManager.GetObject("Image_32_Overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 for average from beginning of activity.
        /// </summary>
        internal static string MAToolTip {
            get {
                return ResourceManager.GetString("MAToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chart Bar.
        /// </summary>
        internal static string Menu_ShowChartBar {
            get {
                return ResourceManager.GetString("Menu_ShowChartBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chart Tools.
        /// </summary>
        internal static string Menu_ShowToolBar {
            get {
                return ResourceManager.GetString("Menu_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average.
        /// </summary>
        internal static string MovingAverage {
            get {
                return ResourceManager.GetString("MovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a non-negative number!.
        /// </summary>
        internal static string NonNegativeNumber {
            get {
                return ResourceManager.GetString("NonNegativeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay of one activity.
        /// </summary>
        internal static string O1 {
            get {
                return ResourceManager.GetString("O1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay of {0} activities.
        /// </summary>
        internal static string O2 {
            get {
                return ResourceManager.GetString("O2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay chart.
        /// </summary>
        internal static string OverlayChart {
            get {
                return ResourceManager.GetString("OverlayChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set filter width.
        /// </summary>
        internal static string SetMovingAveragePeriod {
            get {
                return ResourceManager.GetString("SetMovingAveragePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set activity offset.
        /// </summary>
        internal static string SetOffset {
            get {
                return ResourceManager.GetString("SetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set activity offset with Unique Routes Common Stretches.
        /// </summary>
        internal static string SetOffsetWithUR {
            get {
                return ResourceManager.GetString("SetOffsetWithUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table settings.
        /// </summary>
        internal static string TableSettings {
            get {
                return ResourceManager.GetString("TableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Map Overlay.
        /// </summary>
        internal static string TrailPointsControlLayer {
            get {
                return ResourceManager.GetString("TrailPointsControlLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ZoomToContent {
            get {
                object obj = ResourceManager.GetObject("ZoomToContent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
