//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracksPerformancePredictorPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportTracksPerformancePredictorPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add distance.
        /// </summary>
        internal static string AddDistance {
            get {
                return ResourceManager.GetString("AddDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted pace (min/{0}).
        /// </summary>
        internal static string AdjustedPace {
            get {
                return ResourceManager.GetString("AdjustedPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted speed ({0}/h).
        /// </summary>
        internal static string AdjustedSpeed {
            get {
                return ResourceManager.GetString("AdjustedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted time.
        /// </summary>
        internal static string AdjustedTime {
            get {
                return ResourceManager.GetString("AdjustedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted VDOT.
        /// </summary>
        internal static string AdjustedVDOT {
            get {
                return ResourceManager.GetString("AdjustedVDOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (meter).
        /// </summary>
        internal static string DistanceMeters {
            get {
                return ResourceManager.GetString("DistanceMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance used in models.
        /// </summary>
        internal static string DistancesUsed {
            get {
                return ResourceManager.GetString("DistancesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy aerobic zone.
        /// </summary>
        internal static string EasyAerobicZone {
            get {
                return ResourceManager.GetString("EasyAerobicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of part ({0}).
        /// </summary>
        internal static string EndOfPart {
            get {
                return ResourceManager.GetString("EndOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated pace (min/{0}).
        /// </summary>
        internal static string EstimatedPace {
            get {
                return ResourceManager.GetString("EstimatedPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated speed ({0}/h).
        /// </summary>
        internal static string EstimatedSpeed {
            get {
                return ResourceManager.GetString("EstimatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time.
        /// </summary>
        internal static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High aerobic zone.
        /// </summary>
        internal static string HighAerobicZone {
            get {
                return ResourceManager.GetString("HighAerobicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score plugin integration.
        /// </summary>
        internal static string HighScorePluginIntegration {
            get {
                return ResourceManager.GetString("HighScorePluginIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HourShort {
            get {
                return ResourceManager.GetString("HourShort", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_PerformancePredictor {
            get {
                object obj = ResourceManager.GetObject("Image_16_PerformancePredictor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24_PerformancePredictor {
            get {
                object obj = ResourceManager.GetObject("Image_24_PerformancePredictor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32_PerformancePredictor {
            get {
                object obj = ResourceManager.GetObject("Image_32_PerformancePredictor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval split times.
        /// </summary>
        internal static string IntervalSplitTimes {
            get {
                return ResourceManager.GetString("IntervalSplitTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 (min/{0}).
        /// </summary>
        internal static string k10Pace {
            get {
                return ResourceManager.GetString("k10Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10k ({0}/h).
        /// </summary>
        internal static string k10Speed {
            get {
                return ResourceManager.GetString("k10Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5k (min/{0}).
        /// </summary>
        internal static string k5Pace {
            get {
                return ResourceManager.GetString("k5Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5k ({0}/h).
        /// </summary>
        internal static string k5Speed {
            get {
                return ResourceManager.GetString("k5Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathon.
        /// </summary>
        internal static string Marathon {
            get {
                return ResourceManager.GetString("Marathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile.
        /// </summary>
        internal static string Mile {
            get {
                return ResourceManager.GetString("Mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile (min/{0}).
        /// </summary>
        internal static string MilePace {
            get {
                return ResourceManager.GetString("MilePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile ({0}/h).
        /// </summary>
        internal static string MileSpeed {
            get {
                return ResourceManager.GetString("MileSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteShort {
            get {
                return ResourceManager.GetString("MinuteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod aerobic zone.
        /// </summary>
        internal static string ModAerobicZone {
            get {
                return ResourceManager.GetString("ModAerobicZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go the athlete view and set your maximal heart rate to see the results..
        /// </summary>
        internal static string NoMaxHR {
            get {
                return ResourceManager.GetString("NoMaxHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seed activity.
        /// </summary>
        internal static string NoSeedActivity {
            get {
                return ResourceManager.GetString("NoSeedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace (min/{0}).
        /// </summary>
        internal static string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace for tempo runs.
        /// </summary>
        internal static string PaceForTempoRuns {
            get {
                return ResourceManager.GetString("PaceForTempoRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace for tempo runs of 20 to 60 minutes at VDOT {0:0.0}.
        /// </summary>
        internal static string PaceForTempoRuns_label {
            get {
                return ResourceManager.GetString("PaceForTempoRuns_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 min run is at lactate threshold pace - pace of longer runs adjusted to maintain proper intensity..
        /// </summary>
        internal static string PaceRunNotification {
            get {
                return ResourceManager.GetString("PaceRunNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %max HR..
        /// </summary>
        internal static string PercentMaxHR {
            get {
                return ResourceManager.GetString("PercentMaxHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance must be a positive number..
        /// </summary>
        internal static string PositiveNumber {
            get {
                return ResourceManager.GetString("PositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Predictor with High Score plugin on one activity.
        /// </summary>
        internal static string PPHS1 {
            get {
                return ResourceManager.GetString("PPHS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Predictor with High Score plugin on {0} activities.
        /// </summary>
        internal static string PPHS2 {
            get {
                return ResourceManager.GetString("PPHS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted time.
        /// </summary>
        internal static string PredictedTime {
            get {
                return ResourceManager.GetString("PredictedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction model.
        /// </summary>
        internal static string PredictionModel {
            get {
                return ResourceManager.GetString("PredictionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction results.
        /// </summary>
        internal static string PredictionResults {
            get {
                return ResourceManager.GetString("PredictionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of distance to predict time.
        /// </summary>
        internal static string ProcDistUsed {
            get {
                return ResourceManager.GetString("ProcDistUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected adverse impact of high temperatures on {0:0.00} {1} time.
        /// </summary>
        internal static string ProjectedTemperatureImpact {
            get {
                return ResourceManager.GetString("ProjectedTemperatureImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected weight (kg).
        /// </summary>
        internal static string ProjectedWeight {
            get {
                return ResourceManager.GetString("ProjectedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected impact of weight on {0:0.00} {1} time.
        /// </summary>
        internal static string ProjectedWeightImpact {
            get {
                return ResourceManager.GetString("ProjectedWeightImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove distance.
        /// </summary>
        internal static string RemoveDistance {
            get {
                return ResourceManager.GetString("RemoveDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings....
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings? This cannot be undone..
        /// </summary>
        internal static string ResetAllSettingsWarning {
            get {
                return ResourceManager.GetString("ResetAllSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to the athlete view and set your weight to see the results..
        /// </summary>
        internal static string SetWeight {
            get {
                return ResourceManager.GetString("SetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        internal static string ShortLowerCaseKilometer {
            get {
                return ResourceManager.GetString("ShortLowerCaseKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string ShortLowerCaseMinutes {
            get {
                return ResourceManager.GetString("ShortLowerCaseMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        internal static string ShowPace {
            get {
                return ResourceManager.GetString("ShowPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string ShowSpeed {
            get {
                return ResourceManager.GetString("ShowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed ({0}/h).
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of part ({0}).
        /// </summary>
        internal static string StartOfPart {
            get {
                return ResourceManager.GetString("StartOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature impact.
        /// </summary>
        internal static string TemperatureImpact {
            get {
                return ResourceManager.GetString("TemperatureImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance is not adversely affected at 16° C or lower..
        /// </summary>
        internal static string TemperatureNotification {
            get {
                return ResourceManager.GetString("TemperatureNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time prediction.
        /// </summary>
        internal static string TimePrediction {
            get {
                return ResourceManager.GetString("TimePrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train / race HR..
        /// </summary>
        internal static string TrainRaceHR {
            get {
                return ResourceManager.GetString("TrainRaceHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string UnitCentimeter {
            get {
                return ResourceManager.GetString("UnitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string UnitCentimeterShort {
            get {
                return ResourceManager.GetString("UnitCentimeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        internal static string UnitFoot {
            get {
                return ResourceManager.GetString("UnitFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string UnitFootShort {
            get {
                return ResourceManager.GetString("UnitFootShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string UnitInch {
            get {
                return ResourceManager.GetString("UnitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string UnitInchShort {
            get {
                return ResourceManager.GetString("UnitInchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer.
        /// </summary>
        internal static string UnitKilometer {
            get {
                return ResourceManager.GetString("UnitKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string UnitKilometerShort {
            get {
                return ResourceManager.GetString("UnitKilometerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string UnitMeter {
            get {
                return ResourceManager.GetString("UnitMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string UnitMeterShort {
            get {
                return ResourceManager.GetString("UnitMeterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile.
        /// </summary>
        internal static string UnitMile {
            get {
                return ResourceManager.GetString("UnitMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string UnitMileShort {
            get {
                return ResourceManager.GetString("UnitMileShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard.
        /// </summary>
        internal static string UnitYard {
            get {
                return ResourceManager.GetString("UnitYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string UnitYardShort {
            get {
                return ResourceManager.GetString("UnitYardShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used activity start date.
        /// </summary>
        internal static string UsedActivityStartDate {
            get {
                return ResourceManager.GetString("UsedActivityStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used activity start time.
        /// </summary>
        internal static string UsedActivityStartTime {
            get {
                return ResourceManager.GetString("UsedActivityStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used length of activity.
        /// </summary>
        internal static string UsedLengthOfActivity {
            get {
                return ResourceManager.GetString("UsedLengthOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used time of activity.
        /// </summary>
        internal static string UsedTimeOfActivity {
            get {
                return ResourceManager.GetString("UsedTimeOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in chart.
        /// </summary>
        internal static string ViewInChart {
            get {
                return ResourceManager.GetString("ViewInChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in table.
        /// </summary>
        internal static string ViewInTable {
            get {
                return ResourceManager.GetString("ViewInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % VO2 max: {0:0.0}%, VDOT: {1:0.0}.
        /// </summary>
        internal static string VO2MaxVDOT {
            get {
                return ResourceManager.GetString("VO2MaxVDOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Predictor plugin webpage.
        /// </summary>
        internal static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight impact.
        /// </summary>
        internal static string WeighImpact {
            get {
                return ResourceManager.GetString("WeighImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated times and paces are +/- 2 seconds per {0}..
        /// </summary>
        internal static string WeightNotification {
            get {
                return ResourceManager.GetString("WeightNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone / distance.
        /// </summary>
        internal static string ZoneDistance {
            get {
                return ResourceManager.GetString("ZoneDistance", resourceCulture);
            }
        }
    }
}
